# Generated by Django 5.2.8 on 2025-12-06 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_category_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=199)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('active_status', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('Entry_Date', models.DateField()),
                ('Entry_Date_Time', models.DateTimeField()),
                ('choose_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_brand', to='productApp.brand_table')),
                ('choose_multiple_brand', models.ManyToManyField(related_name='brand_table_info', to='productApp.brand_table')),
                ('choose_unique_brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choose_unique_brand', to='productApp.brand_table')),
            ],
        ),
    ]
