# Generated by Django 5.2.8 on 2025-12-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0004_alter_test_table_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_table',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
