# Generated by Django 5.2.8 on 2025-12-06 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0005_alter_test_table_active_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=199)),
                ('slug', models.SlugField(blank=True, max_length=199, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choose_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.brand_table')),
                ('choose_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.category_table')),
            ],
        ),
    ]
