# Generated by Django 5.2.8 on 2025-12-30 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0006_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_img/')),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.product_table')),
            ],
        ),
    ]
